// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getContractsBucket, getEnvironment } from '@/lib/env';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://asdvxynilrurillrhsyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZHZ4eW5pbHJ1cmlsbHJoc3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODA3OTIsImV4cCI6MjA2ODQ1Njc5Mn0.DKR578o9iyMh1xxqfYKFZfXcns0YrbZVzm-bavkZq6g";

const runtimeEnvironment = getEnvironment();
const defaultSchema = (import.meta.env.VITE_SUPABASE_SCHEMA || 'public').toLowerCase();
const stagingSchema = (import.meta.env.VITE_SUPABASE_STAGING_SCHEMA || 'staging').toLowerCase();
const resolvedSchema = runtimeEnvironment === 'staging' ? stagingSchema : defaultSchema;
const contractDocumentsBucket = getContractsBucket();

type ExtendedDatabase = Database & {
  staging: Database['public'];
};

export const CONTRACT_DOCUMENTS_BUCKET = contractDocumentsBucket;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: resolvedSchema,
  },
});
